print("¡Hola, Belén! Esto es mi primer programa en Python con Git.")
print("hola este es mi primer programa con Python")
print("Seguimos aprendiendo Git y Python!!")
print("Modificando en la rama prueba-rama")
print("Mejora en equipo desde mi rama")
print("Nueva mejora desde mi rama! Hoy 06 de Octubre del 2025! hoy se dice SI SE PUEDE!!")